version: '3.8'
services:
  etl-pipeline:
    build: .
    container_name: etl_pipeline
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - ETL_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=etl_db
      - DB_USER=etl_user
      - DB_PASSWORD=etl_pass
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: etl_redis
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:2.8.1
    container_name: etl_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://etl_user:etl_pass@postgres/etl_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
